name: Build and test

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build-and-test:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Format
        run: yarn run format:check
      - name: Lint
        run: yarn run lint
      - name: Spell check
        run: yarn run spellcheck
      - name: Test build
        run: yarn run build
      - name: Run tests
        run: yarn test
