name: Build and test

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Format
        run: yarn run format:check
      - name: Lint
        run: yarn run lint
      - name: Spell check
        run: yarn run spellcheck
      - name: Test build
        run: yarn run build
      - name: Run tests
        run: yarn test
      - name: Run coverage
        run: yarn run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
