name: Test deployment

on:
  pull_request:
    branches: [master]
  push:
    branches-ignore:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Format
        run: yarn run format:check
      - name: Lint
        run: yarn run lint
      - name: Spell check
        run: yarn run spellcheck
      - name: Test build
        run: yarn run build
      - name: Run tests
        run: yarn test
